version: '3'
services:
  frontend:
    image: bekashif/docker:frontend
    build: ./frontend
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    depends_on: 
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: bekashif/docker:backend
    build: ./backend
    expose:
      - "3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev

networks:
  default:
    driver: bridge